#0 building with "default" instance using docker driver

#1 [internal] load .dockerignore
#1 transferring context:
#1 transferring context: 2B done
#1 DONE 0.3s

#2 [internal] load build definition from Dockerfile
#2 transferring dockerfile: 614B done
#2 DONE 0.4s

#3 [internal] load metadata for docker.io/library/alpine:latest
#3 ...

#4 [auth] library/alpine:pull token for registry-1.docker.io
#4 DONE 0.0s

#3 [internal] load metadata for docker.io/library/alpine:latest
#3 DONE 1.5s

#5 [internal] load build context
#5 DONE 0.0s

#6 [ 1/15] FROM docker.io/library/alpine@sha256:0a4eaa0eecf5f8c050e5bba433f58c052be7587ee8af3e8b3910ef9ab5fbe9f5
#6 resolve docker.io/library/alpine@sha256:0a4eaa0eecf5f8c050e5bba433f58c052be7587ee8af3e8b3910ef9ab5fbe9f5
#6 resolve docker.io/library/alpine@sha256:0a4eaa0eecf5f8c050e5bba433f58c052be7587ee8af3e8b3910ef9ab5fbe9f5 0.2s done
#6 sha256:0a4eaa0eecf5f8c050e5bba433f58c052be7587ee8af3e8b3910ef9ab5fbe9f5 1.85kB / 1.85kB done
#6 sha256:eddacbc7e24bf8799a4ed3cdcfa50d4b88a323695ad80f317b6629883b2c2a78 528B / 528B done
#6 sha256:324bc02ae1231fd9255658c128086395d3fa0aedd5a41ab6b034fd649d1a9260 1.47kB / 1.47kB done
#6 sha256:c6a83fedfae6ed8a4f5f7cbb6a7b6f1c1ec3d86fea8cb9e5ba2e5e6673fde9f6 0B / 3.62MB 0.1s
#6 ...

#5 [internal] load build context
#5 transferring context: 5.74MB 0.1s done
#5 DONE 0.4s

#6 [ 1/15] FROM docker.io/library/alpine@sha256:0a4eaa0eecf5f8c050e5bba433f58c052be7587ee8af3e8b3910ef9ab5fbe9f5
#6 sha256:c6a83fedfae6ed8a4f5f7cbb6a7b6f1c1ec3d86fea8cb9e5ba2e5e6673fde9f6 3.62MB / 3.62MB 0.3s
#6 sha256:c6a83fedfae6ed8a4f5f7cbb6a7b6f1c1ec3d86fea8cb9e5ba2e5e6673fde9f6 3.62MB / 3.62MB 0.4s done
#6 extracting sha256:c6a83fedfae6ed8a4f5f7cbb6a7b6f1c1ec3d86fea8cb9e5ba2e5e6673fde9f6 0.1s
#6 extracting sha256:c6a83fedfae6ed8a4f5f7cbb6a7b6f1c1ec3d86fea8cb9e5ba2e5e6673fde9f6 0.2s done
#6 DONE 1.3s

#7 [ 2/15] RUN apk add --update python3-dev py3-cffi gcc linux-headers musl-dev sqlite
#7 0.440 fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/main/x86_64/APKINDEX.tar.gz
#7 0.569 fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/community/x86_64/APKINDEX.tar.gz
#7 0.991 (1/36) Installing libgcc (13.2.1_git20240309-r0)
#7 1.006 (2/36) Installing jansson (2.14-r4)
#7 1.015 (3/36) Installing libstdc++ (13.2.1_git20240309-r0)
#7 1.048 (4/36) Installing zstd-libs (1.5.6-r0)
#7 1.062 (5/36) Installing binutils (2.42-r0)
#7 1.182 (6/36) Installing libgomp (13.2.1_git20240309-r0)
#7 1.203 (7/36) Installing libatomic (13.2.1_git20240309-r0)
#7 1.207 (8/36) Installing gmp (6.3.0-r1)
#7 1.215 (9/36) Installing isl26 (0.26-r1)
#7 1.240 (10/36) Installing mpfr4 (4.2.1-r0)
#7 1.267 (11/36) Installing mpc1 (1.3.1-r1)
#7 1.285 (12/36) Installing gcc (13.2.1_git20240309-r0)
#7 2.647 (13/36) Installing linux-headers (6.6-r0)
#7 2.831 (14/36) Installing musl-dev (1.2.5-r0)
#7 2.961 (15/36) Installing libbz2 (1.0.8-r6)
#7 2.974 (16/36) Installing libexpat (2.6.2-r0)
#7 2.988 (17/36) Installing libffi (3.4.6-r0)
#7 3.001 (18/36) Installing gdbm (1.23-r1)
#7 3.015 (19/36) Installing xz-libs (5.6.1-r3)
#7 3.031 (20/36) Installing mpdecimal (4.0.0-r0)
#7 3.048 (21/36) Installing ncurses-terminfo-base (6.4_p20240420-r0)
#7 3.075 (22/36) Installing libncursesw (6.4_p20240420-r0)
#7 3.091 (23/36) Installing libpanelw (6.4_p20240420-r0)
#7 3.102 (24/36) Installing readline (8.2.10-r0)
#7 3.114 (25/36) Installing sqlite-libs (3.45.3-r1)
#7 3.135 (26/36) Installing python3 (3.12.3-r1)
#7 3.459 (27/36) Installing python3-pycache-pyc0 (3.12.3-r1)
#7 3.701 (28/36) Installing pyc (3.12.3-r1)
#7 3.705 (29/36) Installing py3-cparser-pyc (2.22-r1)
#7 3.735 (30/36) Installing py3-cffi-pyc (1.16.0-r1)
#7 3.747 (31/36) Installing python3-pyc (3.12.3-r1)
#7 3.752 (32/36) Installing py3-cparser (2.22-r1)
#7 3.766 (33/36) Installing py3-cffi (1.16.0-r1)
#7 3.795 (34/36) Installing pkgconf (2.2.0-r0)
#7 3.800 (35/36) Installing python3-dev (3.12.3-r1)
#7 4.573 (36/36) Installing sqlite (3.45.3-r1)
#7 4.600 Executing busybox-1.36.1-r29.trigger
#7 4.608 OK: 301 MiB in 50 packages
#7 DONE 10.8s

#8 [ 3/15] RUN python3 -m ensurepip
#8 3.319 error: externally-managed-environment
#8 3.319 
#8 3.319 × This environment is externally managed
#8 3.319 ╰─> 
#8 3.319     The system-wide python installation should be maintained using the system
#8 3.319     package manager (apk) only.
#8 3.319     
#8 3.319     If the package in question is not packaged already (and hence installable via
#8 3.319     "apk add py3-somepackage"), please consider installing it inside a virtual
#8 3.319     environment, e.g.:
#8 3.319     
#8 3.319     python3 -m venv /path/to/venv
#8 3.319     . /path/to/venv/bin/activate
#8 3.319     pip install mypackage
#8 3.319     
#8 3.319     To exit the virtual environment, run:
#8 3.319     
#8 3.319     deactivate
#8 3.319     
#8 3.319     The virtual environment is not deleted, and can be re-entered by re-sourcing
#8 3.319     the activate file.
#8 3.319     
#8 3.319     To automatically manage virtual environments, consider using pipx (from the
#8 3.319     pipx package).
#8 3.319 
#8 3.319 note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
#8 3.319 hint: See PEP 668 for the detailed specification.
#8 3.723 Traceback (most recent call last):
#8 3.723   File "<frozen runpy>", line 198, in _run_module_as_main
#8 3.723   File "<frozen runpy>", line 88, in _run_code
#8 3.723   File "/usr/lib/python3.12/ensurepip/__main__.py", line 5, in <module>
#8 3.724     sys.exit(ensurepip._main())
#8 3.724              ^^^^^^^^^^^^^^^^^
#8 3.724   File "/usr/lib/python3.12/ensurepip/__init__.py", line 284, in _main
#8 3.724     return _bootstrap(
#8 3.724            ^^^^^^^^^^^
#8 3.724   File "/usr/lib/python3.12/ensurepip/__init__.py", line 200, in _bootstrap
#8 3.724     return _run_pip([*args, *_PACKAGE_NAMES], additional_paths)
#8 3.724            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#8 3.724   File "/usr/lib/python3.12/ensurepip/__init__.py", line 101, in _run_pip
#8 3.724     return subprocess.run(cmd, check=True).returncode
#8 3.725            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#8 3.725   File "/usr/lib/python3.12/subprocess.py", line 571, in run
#8 3.725     raise CalledProcessError(retcode, process.args,
#8 3.725 subprocess.CalledProcessError: Command '['/usr/bin/python3', '-W', 'ignore::DeprecationWarning', '-c', '\nimport runpy\nimport sys\nsys.path = [\'/tmp/tmp8qy7td_9/pip-24.0-py3-none-any.whl\'] + sys.path\nsys.argv[1:] = [\'install\', \'--no-cache-dir\', \'--no-index\', \'--find-links\', \'/tmp/tmp8qy7td_9\', \'pip\']\nrunpy.run_module("pip", run_name="__main__", alter_sys=True)\n']' returned non-zero exit status 1.
#8 ERROR: process "/bin/sh -c python3 -m ensurepip" did not complete successfully: exit code: 1
------
 > [ 3/15] RUN python3 -m ensurepip:
3.724            ^^^^^^^^^^^
3.724   File "/usr/lib/python3.12/ensurepip/__init__.py", line 200, in _bootstrap
3.724     return _run_pip([*args, *_PACKAGE_NAMES], additional_paths)
3.724            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
3.724   File "/usr/lib/python3.12/ensurepip/__init__.py", line 101, in _run_pip
3.724     return subprocess.run(cmd, check=True).returncode
3.725            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
3.725   File "/usr/lib/python3.12/subprocess.py", line 571, in run
3.725     raise CalledProcessError(retcode, process.args,
3.725 subprocess.CalledProcessError: Command '['/usr/bin/python3', '-W', 'ignore::DeprecationWarning', '-c', '\nimport runpy\nimport sys\nsys.path = [\'/tmp/tmp8qy7td_9/pip-24.0-py3-none-any.whl\'] + sys.path\nsys.argv[1:] = [\'install\', \'--no-cache-dir\', \'--no-index\', \'--find-links\', \'/tmp/tmp8qy7td_9\', \'pip\']\nrunpy.run_module("pip", run_name="__main__", alter_sys=True)\n']' returned non-zero exit status 1.
------
Dockerfile:3
--------------------
   1 |     FROM alpine
   2 |     RUN apk add --update python3-dev py3-cffi gcc linux-headers musl-dev sqlite
   3 | >>> RUN python3 -m ensurepip
   4 |     RUN pip3 install --upgrade pip
   5 |     RUN pip3 install flask
--------------------
ERROR: failed to solve: process "/bin/sh -c python3 -m ensurepip" did not complete successfully: exit code: 1
Duration: 0:18.40